[package]
name = "pdf"
version = "0.1.0"
edition = "2021"

[dependencies]
layout = { path = "../layout" }

allsorts = { version = "^0.11" }

indexmap = { version = "^1.8" }
log = { version = "^0.4", default-features = false }
ouroboros = { version = "0.15" }
printpdf = { version = "^0.5" }
